
- name: Disable the default Redis module
  ansible.builtin.command: dnf module disable -y redis
  become: true

- name: Enable Redis 6 module
  ansible.builtin.command: dnf module enable redis:6 -y
  become: true

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: present
  become: true

- name: Update Redis listen address 1
  ansible.builtin.replace:
   path: /etc/redis.conf
   regexp: '127.0.0.1'
   replace: '0.0.0.0'

- name: Update Redis listen address 2
  ansible.builtin.replace:
   path: /etc/redis.conf
   regexp: '127.0.0.1'
   replace: '0.0.0.0' 


- name: Start Redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true
  
