  # echo -e "${color} Install Maven ${nocolor}"
  # dnf install maven -y  &>>$log_file
  # stat_check $?

  # app_presetup

  # echo -e "${color} Download Maven Dependencies ${nocolor}"
  # cd /app
  # mvn clean package  &>>$log_file
  # mv target/${component}-1.0.jar ${component}.jar  &>>$log_file
  # stat_check $?

  # mysql_schema_setup
  # systemd_setup


- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Load App prequisites
  ansible.builtin.import_tasks:
   file: app_presetup.yml

- name: Download Maven Dependencies
  ansible.builtin.command: 
    cmd: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.jar
    args:
      chdir: /app
  
- name: Mysql Schema Setup
  ansible.builtin.import_tasks:
   file: mysql_schema_setup.yml

- name: Load systemD setup file
  ansible.builtin.import_tasks:
   file: systemd_setup.yml  